### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by secwxx** [iamckn/chained-wireguard-ansible#1]
my test env is:
GCP ubuntu 16
sames not work, when ip forward setted, client has no internet.

ip route add 0.0.0.0/0 dev wg0client table middleman
ip rule add from 10.0.2.0/24 lookup middleman

chains failed.

**Comment by iamckn** [comment]
Share the following: traceroute to the internet from both the client and the middleman, ip route for both client and middleman, tcpdump capture logs for both vpn interfaces on the middleman.

**Comment by freddong** [comment]
when follow step 6 in https://www.ckn.io/blog/2017/12/28/wireguard-vpn-chained-setup
> wg set gate0 peer <peer_public_key> allowed-ips 0.0.0.0/0

you should set "peer_public_key" to PUB4 in the output of "wg show", not PUB3.

```
root@middleman:~# wg show
interface: wg0
  public key: PUBPUB1
  private key: (hidden)
  listening port: 51820

peer: PUB2
  endpoint: CLIENT_IP:51135
  allowed ips: 10.200.200.2/32
  latest handshake: 18 seconds ago
  transfer: 1.83 MiB received, 24.13 MiB sent

interface: gate0
  public key: PUB3
  private key: (hidden)
  listening port: 44287

peer: PUB4
  endpoint: GATE_IP:51820
  allowed ips: 0.0.0.0/0
  latest handshake: 1 minute, 40 seconds ago
  transfer: 19.92 MiB received, 1.36 MiB sent
  persistent keepalive: every 21 seconds
```
on the middleman.

**Comment by secwxx** [comment]
> when follow step 6 in https://www.ckn.io/blog/2017/12/28/wireguard-vpn-chained-setup
> 
> > wg set gate0 peer <peer_public_key> allowed-ips 0.0.0.0/0
> 
> you should set "peer_public_key" to PUB4 in the output of "wg show", not PUB3.
> 
> ```
> root@middleman:~# wg show
> interface: wg0
>   public key: PUBPUB1
>   private key: (hidden)
>   listening port: 51820
> 
> peer: PUB2
>   endpoint: CLIENT_IP:51135
>   allowed ips: 10.200.200.2/32
>   latest handshake: 18 seconds ago
>   transfer: 1.83 MiB received, 24.13 MiB sent
> 
> interface: gate0
>   public key: PUB3
>   private key: (hidden)
>   listening port: 44287
> 
> peer: PUB4
>   endpoint: GATE_IP:51820
>   allowed ips: 0.0.0.0/0
>   latest handshake: 1 minute, 40 seconds ago
>   transfer: 19.92 MiB received, 1.36 MiB sent
>   persistent keepalive: every 21 seconds
> ```
> 
> on the middleman.

thanks, I think I figuared it out, problem solved!
love you !
