### ISSUE TITLE
pf firewall

### ISSUE THREAD

**Issue by erictwo** [iamckn/chained-wireguard-ansible#3]
Great work iamckn! I was wondering if you are familiar with openbsd pf firewall, if you are would you happen to know the translation of the SNAT rule in step 4 on middleman?

  name: Set up vpn chain NAT 
   iptables:
     table: nat
     chain: POSTROUTING
     source: 10.200.200.0/24
     to_source: 10.100.100.2
     jump: SNAT

Both interfaces are up and running. I have tried a few nat-to without success thinking maybe rdr-to. Thanks for the project and great documentation

**Comment by iamckn** [comment]
Unfortunately I haven't interacted with openbsd much. Hopefully someone who has can assist.
